name:                hcompress
version:             0.1.0.0
github:              "kozlovskym/hcompress"
license:             MIT
author:              "Martin Kozlovský"
maintainer:          "example@example.com"
copyright:           "2022 Martin Kozlovský"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kozlovskym/hcompress#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- utf8-string
- containers
- pqueue
- yjtools

library:
  source-dirs: src

executables:
  hcompress-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -O2
    dependencies:
    - hcompress
    - optparse-applicative

tests:
  hcompress-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hcompress
    - HUnit
    - process
    - directory
