name:                huffman
version:             0.1.0.0
github:              "kozlov721/huffman"
license:             MIT
author:              "Martin Kozlovský"
# maintainer:          "example@example.com"
copyright:           "2022 Martin Kozlovský"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kozlov721/huffman#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring >= 0.11.1.0
- utf8-string
- containers
- pqueue
- bitstring

library:
  source-dirs: src

executables:
  huffman:
    main:                Main.hs
    source-dirs:         app

    ghc-options:
      - -O2
      - -threaded

    dependencies:
    - huffman
    - optparse-applicative
    - extra

tests:
  huffman-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -rtsopts
    - -with-rtsopts=-N
    - -threaded
    dependencies:
    - huffman
    - HUnit
